### ISSUE TITLE
error: EOF

### ISSUE THREAD

**Issue by goosegit11** [j178/chatgpt#10]
When I talk to ChatGPT for a while, it suddenly gives an "error: EOF" and stops responding.

Arch Linux, st terminal, zsh 

![image](https://user-images.githubusercontent.com/89806596/222974642-53051e02-2b63-499f-a47c-67d28f9b6654.png)

**Comment by Sakurageng** [comment]
me too

**Comment by j178** [comment]
thanks for the report, I'll look into this.

**Comment by j178** [comment]
Hi, I just release [v0.2](https://github.com/j178/chatgpt/releases/tag/v0.2.0), this issue may be resolved, could you try it?
