### ISSUE TITLE
add basic actions like Ctrl + Arrows

### ISSUE THREAD

**Issue by goosegit11** [j178/chatgpt#16]
Ctrl + Up: your last sentence
Ctrl + Left: move one word to the left
Ctrl + Right: move one word to the right

**Comment by j178** [comment]
Text input relies on the textarea implementation of bubbletea, which comes with built-in support for some shortcut keys:
https://github.com/charmbracelet/bubbles/blob/78a82d1616ddfab1d47c7c9051926b900e9e4017/textarea/textarea.go#L62-L87

> it would be nice to integrate shell functions into the program

It can be a bit challenging to implement using Bubble Tea, perhaps you could try https://github.com/diemus/chatgpt.

**Comment by goosegit11** [comment]
> perhaps you could try https://github.com/diemus/chatgpt.

it's cool, but it too doesn't have ctrl + arrows functionality :-(

**Comment by j178** [comment]
@goosegit11 Hi, this `ctrl+up` and `ctrl+down` shortcuts are supported in #19 .
