### ISSUE TITLE
[Feature] GPT-4 support

### ISSUE THREAD

**Issue by xilopaint** [j178/chatgpt#22]
Any plans to make the CLI work with GPT-4?

**Comment by j178** [comment]
@xilopaint Hi, thanks for the advice. I added custom model support in #23, you are able to use GPT-4 model by creating a config file in `~/.config/chatgpt.json`:
```json
{
    "model": "gpt-4"
}
```

What's more, you are able to change default prompt, tweak parameters like `temperature`, `max_tokens` and `stream`.

**Comment by j178** [comment]
Changed config file location to `~/.config/chatgpt/config.json` in https://github.com/j178/chatgpt/commit/ae0320856326cf3287aae4b79f0254c6ec4b9160

**Comment by xilopaint** [comment]
That's a better fit. Thanks!
