### ISSUE TITLE
Export and save  conversations

### ISSUE THREAD

**Issue by Yikai-Liao** [j178/chatgpt#26]
Can you add the function of saving history automatically and exporting conversation as markdown?

**Comment by Yikai-Liao** [comment]
For example, when I want to share an entire conversation with a friend or need to quickly copy all the code or tables, mind maps, etc. that ChatGPT has generated for me.

**Comment by j178** [comment]
Thank you for advice, history saving has been added in #29. But I still can not figure not how to implement the exporting, are you interested in makeing a PR?
Closed as completed, feel free to create a new one.
