### ISSUE TITLE
When the generated content is too long, it gets obscured, especially the code.

### ISSUE THREAD

**Issue by hardy4yooz** [j178/chatgpt#27]
![image](https://user-images.githubusercontent.com/4044094/226515380-74dec325-0731-4998-8355-143acf592676.png)

I can't see what I previously typed anymore, and I can't even see the entire code block.

**Comment by j178** [comment]
You can use <kbd>↑</kbd> or <kbd>page up</kbd> to scroll through the view port.

![image](https://user-images.githubusercontent.com/10510431/226515639-4ca2c7e4-4c80-4e40-bc55-9ea860c01de9.png)

**Comment by hardy4yooz** [comment]
`↑`  works in `warp` but not in `iTerm2`.

**Comment by j178** [comment]
I am using `iTerm2`, and <kbd>↑</kdb> works well.

> On the other hand, using up and down arrows to navigate through recently used input is a better choice.

I agree, will think how to improve this.

**Comment by j178** [comment]
Changed <kbd>↑</kbd> and <kbd>↓</kbd> to navigate through input history in https://github.com/j178/chatgpt/commit/6b0dca5fc788c951347c9a3c9991f4ac3547447c, will be available in next version.
