### ISSUE TITLE
Create Homebrew Core formula

### ISSUE THREAD

**Issue by xilopaint** [j178/chatgpt#34]
I think this project is already popular enough to be included in Homebrew Core.

**Comment by j178** [comment]
Thank you for suggesting.
However, I would like to clarify that this is just a simple toy project and a basic API wrapper. It is not intended for long-term maintenance, and therefore may not be suitable for inclusion in Homebrew Core. 
And the current installation method is very easy, having it as a core formula would not make a significant difference. Additionally, having it as a core formula may also slow down the release process.  I don't think it is necessary to include this project in Homebrew Core at this time.

**Comment by xilopaint** [comment]
It would not slow down the release process, but you're right. If it's not intended for long-term maintenance it's not [acceptable formula](https://docs.brew.sh/Acceptable-Formulae). Thanks for your work anyway, this is the best ChatGPT shell I've found. Love the design.

**Comment by j178** [comment]
Thank you ❤️
