### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by mayankdutta** [j178/chatgpt#44]
Hello. 
I started conversation by saying `hii`
Every time error shows up saying `error: Unexpected EOF, Please try again`.
 

![Screenshot 2023-03-29 at 7 27 54 PM](https://user-images.githubusercontent.com/33067129/228562199-b441d1dd-427b-4ec7-8f69-fe8da6fb409b.png)

**Comment by j178** [comment]
Can you access the `api.openai.com` directly?

**Comment by mayankdutta** [comment]
no, showing me `invalid URL`

**Comment by j178** [comment]
Could you please try running `echo hi | chagpt` and let me know if there are any errors?



> showing me `invalid URL`

What is showing this? a browser?

**Comment by mayankdutta** [comment]
this

![Screenshot 2023-03-29 at 7 44 12 PM](https://user-images.githubusercontent.com/33067129/228566765-9401549f-56ea-4324-8b3e-d656bcf300d9.png)

**Comment by mayankdutta** [comment]
```
2023/03/29 19:45:33 error, status code: 429, message: You exceeded your current quota, please check your plan and billing details.
```

**Comment by j178** [comment]
seems like you have exceeded your API quata :(

**Comment by mayankdutta** [comment]
thanks for your time, 
will have to go for new account i think !!
