### ISSUE TITLE
Use value of -p as the prompt if it can't be found as a key in the config (feature proposal)

### ISSUE THREAD

**Issue by bkis** [j178/chatgpt#47]
This way you could either use a predefined prompt (`chatgpt -p translate`) or come up with one on the fly (`chatgpt -p "You are a cat. You can only meow. That's it."`).

**Comment by j178** [comment]
Hi, thanks for the advice. This is exactly how `chatgpt` works now.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/10510431/229424373-73e75b63-4968-4ec4-ae45-7b2a7a02e0b9.png">

**Comment by bkis** [comment]
Oh, great :)  
Sorry I didn't just try it - couldn't find it mentioned in the documentation.

Thanks for this great tool! Works flawlessly and the interactive CLI is very well designed and efficient!
