### ISSUE TITLE
not using `http_proxy`, `https_proxy` env var on windows

### ISSUE THREAD

**Issue by baymax55** [j178/chatgpt#53]
![image](https://user-images.githubusercontent.com/35788491/229660422-620088ce-6fea-4ec0-b8e4-94e86654b59e.png)

**Comment by baymax55** [comment]
error: Post "https://api.openai.com/v1/chat/completions": dial tcp 111.243.214.169:443: connectex: A connection attempt

**Comment by j178** [comment]
`chatgpt` supports `http_proxy` and `https_proxy` out of box.

In PowerShell, you should use `$env:http_proxy='http://172.16.11.11:7890/'` to set the environment variable.

**Comment by baymax55** [comment]
> `chatgpt` supports `http_proxy` and `https_proxy` out of the box.
> 
> In PowerShell, you should use `$env:http_proxy='http://172.16.11.11:7890/'` to set the environment variable.

still not wokring

![image](https://user-images.githubusercontent.com/35788491/229679929-f8fb20fa-5e6a-4190-b4a6-119c4d4a2b00.png)


but it works when use `curl google.com -v` in PowerShell

![image](https://user-images.githubusercontent.com/35788491/229680139-8abf533c-320d-4039-b6b5-ad772f08c866.png)

**Comment by j178** [comment]
Thanks, I'll look into it.

**Comment by baymax55** [comment]
![image](https://user-images.githubusercontent.com/35788491/229799822-64c6a7ad-2090-41bd-a75f-ae233cce744b.png)


![image](https://user-images.githubusercontent.com/35788491/229800087-761177be-8fa7-4582-b05e-8d1b402db56c.png)


> Hi, I can't reproduce this on my Windows 11 machine. ![image](https://user-images.githubusercontent.com/10510431/229784277-47953aa3-45ca-4ae0-8793-a9f002425932.png)
> 
> From previous example, `chatgpt` is indeed using the env var for proxy.
