### ISSUE TITLE
error: unexpected EOF

### ISSUE THREAD

**Issue by Puuaru** [j178/chatgpt#54]
![image](https://user-images.githubusercontent.com/38312096/229682044-d40e1d1c-1595-437e-a66e-4dc86df19490.png)
have tried any endpoint or using proxy, and perform the same

**Comment by j178** [comment]
please run `echo hello | chatgpt` and see if there are any errors.

**Comment by Puuaru** [comment]
fine, it is because my free trial was expired

**Comment by ylyhappy-hello** [comment]
> fine, it is because my free trial was expired

hello, can you tell me , how to continue use chatgpt, when firee trail was expired
