### ISSUE TITLE
Why not a scroll bar?

### ISSUE THREAD

**Issue by SinisterSup** [j178/chatgpt#61]
**Scroll Bar** as an enhanced feature!

To a feature very good like this, it just needs a scroll bar. It would help if we wanted to copy a pretty long piece of code as a response by the chatGPT. Also, it makes a lot of difference when you want to type in, a whole lot of information to the prompt and review it back. If done so... you are building the very ditto clone of chatGPT in the command line!

**Comment by j178** [comment]
Thanks for your advice. 

There are numerous limitations when working with a terminal, which makes it hard, or even impossible, to simulate a scroll bar. I will explore potential solutions to do this.
