### ISSUE TITLE
能把configDir函数改为public吗？

### ISSUE THREAD

**Issue by moqsien** [j178/chatgpt#63]
我想自己定制一下，不想把配置文件都放在现在的默认目录下。
但是configDir这个方法又是个私有方法。

可不可以改成公有的开放出来呢？

**Comment by j178** [comment]
可以是可以，但就算改成公开的你也覆盖不了它呀？你是想修改源码自己编译一个版本吗？那直接修改 configDir 的实现就好了吧

**Comment by moqsien** [comment]
> 可以是可以，但就算改成公开的你也覆盖不了它呀？你是想修改源码自己编译一个版本吗？那直接修改 configDir 的实现就好了吧

我是想把chatgpt这个项目当做库使用，导入到自己的项目中，做二次开发，并不是直接编译使用它。

**Comment by j178** [comment]
可能不太行得通，这个项目大部分代码都在 main package 里，应该没办法作为 library 引用。另外 go 里应该也没办法覆盖其他 module 的 public 方法吧？
