### ISSUE TITLE
Prompt Not Resetting when `-p` is used.

### ISSUE THREAD

**Issue by piercecohen1** [j178/chatgpt#65]
The prompt is not resetting when `-p` is used until the conversation is cleared manually with the `ctrl+r` keybinding. Also, it was always choosing the default prompt for me even when I specified a different prompt, but I was modify my code to fix that issue.

**Comment by j178** [comment]
Hi, could you please elaborate on how you fixed this issue?

I created PR #66, which sets the prompt of the current conversation to the one provided with the `-p` flag. Does this fix your issue?

**Comment by piercecohen1** [comment]
This fixes the issue. My solution was very similar. PR #66 fully addressed the issues I was having. Thanks!
