### ISSUE TITLE
command not found: chatgpt

### ISSUE THREAD

**Issue by laraconda** [j178/chatgpt#75]
I installed the package using go as instructed in the README. Yet, I can't run the command.

I have never used go before so I don't really know where the installed module is.

Go version: go1.21
OS: Debian 11
Shell: ZSH

**Comment by j178** [comment]
from `go help install`:
```
Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set.
```
