### ISSUE TITLE
Windows WSL2 Support

### ISSUE THREAD

**Issue by surgiie** [j178/chatgpt#76]
Not sure if there is something wrong on my end here but the interactive cli doesnt appear to render well in WSL2/Ubuntu for windows

The prompt input text duplicates itself for each letter I  type as seen here:

![image](https://github.com/j178/chatgpt/assets/12025002/a6ee01e0-117c-4a3c-99f0-89ad7fe6fec3)

Am I missing something here or is there no support for this?

Im on windows 10 and using the latest version of the CLI thats available on brew.

**Comment by j178** [comment]
The nerd font icon doesn’t display correctly on the Windows terminal if you haven’t installed nerd font. 
In v1.2.1, I’ve removed those nerd font icons. Please test it out.
