### ISSUE TITLE
feat: custom keybindings

### ISSUE THREAD

**Issue by mmngreco** [j178/chatgpt#78]
Hello there! 

First of all, I want to express my gratitude for this fantastic project. The work done here is truly impressive. While using it, I noticed that some keybindings are difficult to remember because they are subjective in nature. For example, As a Vim user, I find the Ctrl+Left key combination unpleasant. Therefore, I was wondering if it would be possible for users to define their own keybindings, perhaps in the configuration file. It would greatly enhance the overall user experience. Thank you!

**Comment by j178** [comment]
Thanks!  I think this feature is feasible and I'll explore how to implement it. Feel free to send a PR if you'd like to contribute.

**Comment by j178** [comment]
v1.3 is out with the ability to change default key bindings, please try it out!

**Comment by mmngreco** [comment]
Wow, amazing! I will try it and come back with the feedback. Thanks a lot for your effort on this ❤️🙏

**Comment by mmngreco** [comment]
Hey @j178, I've tried but it seems there is some wrong:

![image](https://github.com/j178/chatgpt/assets/6231413/04e57e5f-6bc5-4bc5-a32f-5118c1851ea3)

I've used `go install ....@latest` but v1.3 is not detected :-/

**Comment by j178** [comment]
You downloaded arm64 linux version binary, are you running it on an arm64 linux machine?

The `go install` command not working is because I pushed an invalid version number `v1.3` (should be `v1.3.0`). I fixed it. You can try running `go install github.com/j178/chatgpt/cmd/chatgpt@latest` again. Thank you.

**Comment by mmngreco** [comment]
> You downloaded arm64 linux version binary, are you running it on an arm64 linux machine?

:facepalm:  you're right! 

> I fixed it. You can try running go install github.com/j178/chatgpt/cmd/chatgpt@latest again. Thank you.

Sweet, thank you!

**Comment by mmngreco** [comment]
Amazing work done here. it works like a charm, I love it! Thank you!
