### ISSUE TITLE
Add Support for the latest models. 

### ISSUE THREAD

**Issue by ziova** [j178/chatgpt#80]
Hi, can you please add support for the latest turbo model of GPT-4 given it's cost. Right now the application throws an error when I have the following; 

`    "model": "gpt-4-1106-previe",
`

**Comment by j178** [comment]
Thansk for the report! The model check has been removed in https://github.com/j178/chatgpt/commit/d217301f775bd1ec882cc18b00d6954364f9ddea and released in [v1.3.1](https://github.com/j178/chatgpt/releases/tag/v1.3.1)
