### ISSUE TITLE
bug: long text auto wrap in viewport

### ISSUE THREAD

**Issue by j178** [j178/chatgpt#9]

**Comment by caster8013** [comment]
Same problem, looking forward to its fix.

**Comment by adsian** [comment]
> _No description provided._

![image](https://user-images.githubusercontent.com/34738478/223050106-ffbdc07c-5256-4b1b-b4fb-7718546a8aba.png)
遇到过长的回答, 不会换行

**Comment by adsian** [comment]
提了 pr @j178

**Comment by j178** [comment]
Hi, I just release [v0.2](https://github.com/j178/chatgpt/releases/tag/v0.2.0), this issue may be resolved, could you try it?

**Comment by caster8013** [comment]
> Hi, I just release [v0.2](https://github.com/j178/chatgpt/releases/tag/v0.2.0), this issue may be resolved, could you try it?

<img width="1412" alt="Screen Shot 2023-03-07 at 13 11 19" src="https://user-images.githubusercontent.com/11721318/223326573-ce704eb7-511c-4019-b81e-d954e3d08a7d.png">

thanks for the effort! Not resolved as in my env(MBP M1, zsh)!

**Comment by j178** [comment]
The word-wrap for Chinese still has some issues because Chinese characters take up two character spaces, I will try to resolve it.

**Comment by j178** [comment]
@caster8013 Hi, I released a fix in [v0.2.2](https://github.com/j178/chatgpt/releases/tag/v0.2.2), could you try it?

**Comment by caster8013** [comment]
> @caster8013 Hi, I released a fix in [v0.2.2](https://github.com/j178/chatgpt/releases/tag/v0.2.2), could you try it?

It's fixed! Thanks to you for your quick and effective fix of
  this issue! it's very convenient to access chatGPT API in command line except this little obstacle!

**Comment by j178** [comment]
thank you :)
