### ISSUE TITLE
Support gpt-4o

### ISSUE THREAD

**Issue by johannesCmayer** [j178/chatgpt#95]
Please make it such that gpt-4o can be used. I have not figured out how to make it work. I get `Error: invalid model gpt-4o`.

**Comment by iconoclasthero** [comment]
I'd like to see that this option be implemented in a way that would allow the user to force the model to stay in chatgpt-3 rather than let openai.com decide when it switches to 4o as it does with the GUI.  i don't notice any improvements, but when the complimentary time on the 4o model expires, there's often issues.

**Comment by tennox** [comment]
> force the model to stay in chatgpt-3

afaik this is already supported via config file:

`chatgpt/config.json`
```
 {
   "conversation": {
    "model": "gpt-4o"
  }
}
```

**Comment by johannesCmayer** [comment]
@tennox  I tried that
```
chatgpt                                                                                                                                                                                                             
Error: invalid model gpt-4o
```

What am I doing wrong? What part of the source code do I need to change? I tried to search for 2 minutes for a list of models but did not find it.

**Comment by j178** [comment]
@johannesCmayer Hi, sorry for the delay! Could you please share the output of `chatgpt -v`? Thanks!

**Comment by johannesCmayer** [comment]
chatgpt -v                                                                                                                 
dev
commit: HEAD
built at: unknown
goos: linux
goarch: amd64

(I am using unstable NixOS version from 23.11, but I am not sure if this at all helpful to you.)

**Comment by johannesCmayer** [comment]
It [should be](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/misc/chatgpt-cli/default.nix#L22) version v1.3.4

**Comment by j178** [comment]
> ```
> 
> > chatgpt -v
> 
> dev
> 
> commit: HEAD
> 
> built at: unknown
> 
> goos: linux
> 
> goarch: amd64
> 
> ```
> 

seems like it was built from the master branch, not from a pre-built binary release?

**Comment by tennox** [comment]
> unstable NixOS version from 23.11
That's not the latest version, my upgrade to v1.3.4 only made it to 24.05 (or just use unstable):
https://github.com/NixOS/nixpkgs/commit/6a69b2b7647a0918e07f20d98560dfc95718e709

> seems like it was built from the master branch, not from a pre-built binary release?
It's built from the v1.3.4 tag:
https://github.com/j178/chatgpt/tree/v1.3.4


But given both of us having problems having installed via Nix - maybe we are using a wrong version? Does it work for you @j178 ? Will investigate. :thinking:

**Comment by j178** [comment]
Hi @johannesCmayer @tennox 

I justed released [v1.3.5](https://github.com/j178/chatgpt/releases/tag/v1.3.5), which should support GPT-4o, please give it a try!

If you installed it via Nix, it might not be updated yet since the Nix package isn't maintained by me.

Thanks!

**Comment by tennox** [comment]
> I justed released [v1.3.5](https://github.com/j178/chatgpt/releases/tag/v1.3.5) [...]
> If you installed it via Nix, it might not be updated yet since the Nix package isn't maintained by me.

Thanks! I will update the nix package :)

**Comment by tennox** [comment]
**PR**: https://github.com/NixOS/nixpkgs/pull/318547
**Test via**: `nix shell github:tennox/nixpkgs/chatgpt-update-1.3.5#chatgpt-cli`

**Comment by johannesCmayer** [comment]
Works!
