### ISSUE TITLE
install instruction

### ISSUE THREAD

**Issue by iconoclasthero** [j178/chatgpt#97]
I downloaded the git via `$ gh`
Read the README.md.
executed `go install github.com/j178/chatgpt/cmd/chatgpt@latest`
no chatgpt binary anywhere.
executed `go build`
no chatgpt binary anywhere.
executed `sudo go install github.com/j178/chatgpt/cmd/chatgpt@latest`
no chatgpt binary anywhere.

an ubuntu 24.04-like machine.

```
$ find ~/bin/gits -iname chatgpt -type f
$ which chatgpt
$
```

**Comment by j178** [comment]
```
$ go help install
usage: go install [build flags] [packages]

Install compiles and installs the packages named by the import paths.

Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set.
```

Please check if any $GOBIN, $GOPATH env vars are set, and make sure they are in your `PATH`.
